- name: Install Application via URL
  hosts: all
  gather_facts: false

  vars:
    download_url: "" #can be in azure Blob or get the url installer
    dest_path: "C:\\temp\\#filename"

  tasks:
    - name: Ensure Temp Directory Exists
      win_file:
        path: C:\temp
        state: directory

    - name: Download MSI
      win_get_url:
        url: "{{ download_url }}"
        dest: "{{ dest_path }}"

    - name: Install MSI
      win_package:
        path: "{{ dest_path }}"
        state: present
